# TEX = paper.tex
# TEX += motivation.tex
# TEX += experimental_setup.tex
# TEX += results.tex
# TEX += implications.tex
# TEX += threats_to_validity.tex
# TEX += conclusions.tex
TEX = touchdevelop_tutorials.tex
TEX += introduction.tex
TEX += background.tex
TEX += methods.tex
TEX += results.tex
TEX += conclusion.tex
# TEX += touchdevelop_tutorials.aux

FIGS = 

PDF = touchdevelop_tutorials.pdf

all:touchdevelop_tutorials.pdf

touchdevelop_tutorials.pdf: $(TEX) $(FIGS) revision.tex
	@pdflatex touchdevelop_tutorials
	@bibtex touchdevelop_tutorials
	@pdflatex touchdevelop_tutorials
	@pdflatex touchdevelop_tutorials
	
revision.tex: $(TEX)
	@echo "% Autogenerated, do not edit" > revision.tex
	@echo "\\\\newcommand{\\\\revisiondate}{`git log -1 --format=\"%ad\" --date=local`}" >> revision.tex
	@echo "\\\\newcommand{\\\\revision}{`git log -1 --format=\"%h\"`}" >> revision.tex

clean:
	@rm -f *.aux *.bbl *.blg *.log *.pdf
	@rm -rf revision.tex

